name: Life Nutrition
favicon: null
layout_spectrum: 0.13213282567448914
typography_spectrum: 0.86874
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e1e2dd'
    - '#0a0607'
    - '#a9a194'
    - '#6b4228'
    - '#9c6958'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.3601389843970537
  rhythmicContrast: 0.5
purpose: []
