name: Life Nutrition
favicon: null
layout_spectrum: 0.9008
typography_spectrum: 0.91082
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#00c0ff'
    - '#555333'
    - '#b9cb67'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.3601389843970537
  rhythmicContrast: 0.5
purpose: []
