name: KEBNutrition
favicon: null
layout_spectrum: 0.13213282567448914
typography_spectrum: 0.2980812694877386
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.42676446260884404
  lightness: 0.5253740961197764
  saturation: 0.3601389843970537
  rhythmicContrast: 0.4315827591344714
purpose: []
