name: Life Nutrition
favicon: null
layout_spectrum: 0.13213282567448914
typography_spectrum: 0.2980812694877386
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#131313'
    - '#90693e'
    - '#72482e'
    - '#e0dada'
    - '#b8bbce'
  brandStrength: 0.42676446260884404
  lightness: 0.5253740961197764
  saturation: 0.3601389843970537
  rhythmicContrast: 0.4315827591344714
purpose: []
